name = "unsub-push"
main = "unsub-push-worker.js"
compatibility_date = "2024-01-01"

# Cron trigger — 00:00 UTC = 09:00 KST (Korean Standard Time)
[triggers]
crons = ["0 0 * * *"]

# KV namespace for storing push subscriptions (auto-created by deploy workflow)
[[kv_namespaces]]
binding = "PUSH_KV"
id = "3deb12588a364ec9833d9fe4467b6aae"
